export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_NOT_FOUND = 'SET_CURRENT_USER_NOT_FOUND';
export const SET_CURRENT_USER_EXIST = 'SET_CURRENT_USER_EXIST';